### ISSUE TITLE
Potential functions

### ISSUE THREAD

**Issue by NSQY** [Setsugennoao/vs-rgtools#4]
1. Approximated bilateral
    * http://avisynth.nl/index.php/Dither_tools#Dither_bilateral16
    * https://github.com/Dogway/Avisynth-Scripts/blob/master/ExTools.avsi#L1417-L1569
    * https://forum.doom9.org/showpost.php?p=1951322&postcount=304

- Flux5FramesT
    * https://discord.com/channels/856381934052704266/856406641872207903/990134345798914099
    * https://forum.doom9.org/showpost.php?p=1471858&postcount=324

**Comment by Setsugennoao** [comment]
Hello!
Flux5FramesT is already there under the name flux_smooth, under the func submodule.
Will look into the approx bilateral function.

**Comment by Setsugennoao** [comment]
IIRC the original use of the approximated bilateral function was just speed.
For that, I think that the cuda implementation with vspyplugin of bilateral in https://github.com/Irrational-Encoding-Wizardry/vs-rgtools/commit/65a186be7b572d66fdcff2df23a70e4ec53cd61e fixes the issue.

From my testings, with expr, it'll be harder to match these speeds.
I get the point with cpu, though, so feel free to reopen the issue if the approximated bilateral is still needed.
