### ISSUE TITLE
gauss_blur heavy performance loss without approximation

### ISSUE THREAD

**Issue by LightArrowsEXE** [Setsugennoao/vs-rgtools#42]
This commit https://github.com/Jaded-Encoding-Thaumaturgy/vs-rgtools/commit/c6b27072fbdb573ed5714892f9f123988f216384 reportedly caused a severe performance loss when called from retinex. Seems tied to the downscaled gaussian approximation or what-have-you.

For something like retinex, the added precision may not be necessary and introduce needless slowdowns. We should figure out a way to bring the speed back up if possible, be it by introducing a new function for the approximation, adding a parameter, or figuring out a faster way to do an accurate blur.

**Comment by emotion3459** [comment]
TCanny Gauss was brought up as a suggestion some time ago, theres also https://github.com/vapoursynth/vapoursynth/issues/787

**Comment by emotion3459** [comment]
Closing this due to a lack of decent alternatives. This can be reconsidered if an acceptable approximation ever becomes available.

**Comment by shssoichiro** [comment]
Within resize2 itself, the significant majority of the time seems to be spent in `ResizeImplV_U16_AVX2` and `resize_line8_h_u16_avx`. However, the overlying issue with retinex specifically is that it is calling `gauss_blur` with very high numbers of taps. It calls `gauss_blur` 3 times per frame, once with each `sigma` value for the number of `taps`. The default sigma is `[25, 80, 250]`, and `gauss_blur` becomes orders of magnitude slower when called with such high `taps` values as `250`.

That being said, even with this being identified, I'm not sure if there is a good way to change this to improve the performance, without harming quality.
