### ISSUE TITLE
True Gaussian Blur

### ISSUE THREAD

**Issue by nobananasforyou** [Setsugennoao/vs-rgtools#5]
Have you looked at sekrit's True Gaussian Blur port? I thought it might be useful here: https://github.com/HomeOfVapourSynthEvolution/havsfunc/issues/42

**Comment by Setsugennoao** [comment]
Please check if something is already implemented before opening an issue.
It's there under the name `gauss_blur`.

You can also join the discord server.

**Comment by nobananasforyou** [comment]
Okay. My bad,
